#! /bin/sh

xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &

sxhkd &
compton -b &
dunst &

# bspc monitor -d I II III IV V VI VII VIII IX X
main='\uf108' # Computer / Desktop screen
web='\uf0ac' # Globe
dev='\ue795' # Terminal
bspc monitor -d ${main} ${web} ${dev}

bspc config border_width 0.5
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config focus_follows_pointer true

bspc rule -a Chromium focus=on border=off
bspc rule -a termite floating=on border=off
bspc rule -a Screenkey manage=off
bspc rule -a feh floating=on center=true

pgrep -x panel > /dev/null || panel &
