#! /bin/bash
volume() {
    icon=""
    vol=`amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p'| uniq`

    if [ $vol -ge 50 ]; then
        icon="\uf028" # Full Volume Icon
    elif [ $vol -lt 50 ] && [ $vol -ne 0 ]; then
        icon="\uf027" # Halv Volume Icon
    else
        icon="\uf026" # 0 and muted
    fi

    echo -e "${icon} ${vol}"
}

. panel_colors

while :; do
    echo -e "V%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}$(volume)%{B-}%{F-}"
    sleep 1
done
