#! /bin/sh
nowplaying() {
  cur=`mpc current`
  ## this line allow to choose whether the output will scroll or not
  test "$1" = "scroll" && PARSER='skroll -n20 -d0.5 -r' || PARSER='cat'
  test -n "$cur" && $PARSER <<< $cur || echo "-- stopped --"
}

while :; do
    printf "%s\n" "$( nowplaying )"
    sleep 1
done
