#! /bin/bash
cpuload() {
    # LINE=`ps -eo pcpu | grep -vE '^\s*(0.0|%CPU)' | sed -n '1h;$!H;$g;s/\n/ +/gp'`
    # read bc <<< $LINE
    # echo $bc
    echo `cat /proc/loadavg | awk '{print $1}'`
}

. panel_colors

while :; do
    echo -e "P%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}\uf2db $(cpuload) %{B-}%{F-}"
    sleep 5
done
