#! /bin/bash

xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &

sxhkd &
compton -b &
$HOME/.config/polybar/launch.sh &
dunst &
nitrogen --restore &

# bspc monitor -d I II III IV V VI VII VIII IX X
# web='\uf0ac' # Globe
# dev='\ue795' # Terminal

# term='\uf120' # Terminal-Light
# bspc monitor HDMI-1-1 -d ${term}
# bspc monitor DP-1 -d ${term}


# main='\uf108' # Computer / Desktop screen
# web='\uf269' # Firefox
# dev='\uf126' # Code-Branch
# bspc monitor DVI-1-1 -d ${main} ${web} ${dev}
# bspc monitor DP-1 -d "code" "office"
# bspc monitor DVI-1-1 -d "mail"
# bspc monitor HDMI-1 -d "web" "graphics"
bspc monitor DP-0 -d I II
bspc monitor DVI-I-1 -d IV
bspc monitor HDMI-0 -d III V

bspc config border_width 0.5
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

#bspc config focus_by_distance true
#bspc config history_aware_focus true

bspc rule -a firefox focus=on border=off
bspc rule -a alacritty floating=on border=off
bspc rule -a feh floating=on center=true


